### ISSUE TITLE
I want to add some more feature to this repo. let this assign me

### ISSUE THREAD

**Issue by bhaskarkumar1** [savya-ad/Selfie_python#1]
Such as capture the selfie automatically if a smile on the face is detected and Save each selfie

**Comment by savya-ad** [comment]
> Such as capture the selfie automatically if a smile on the face is detected and Save each selfie

@bhaskarkumar1  ok Work on it

**Comment by bhaskarkumar1** [comment]
> > Such as capture the selfie automatically if a smile on the face is detected and Save each selfie
> 
> @bhaskarkumar1 ok Work on it  

@savya-ad  ok Thank you!
